#   CH-230-A 
#   Makefile.txt
#   Rumen Mitov
#   rmitov@jacobs-university.de 


# compiler options
CC = gcc
CFLAGS = -Wall

# object file variables
OBJ = use_linked_list.o linked_list.o

use_linked_list.o : linked_list.h use_linked_list.c
linked_list.o : linked_list.h linked_list.c

# make object files
objects : $(OBJ)

# build executable
build : objects
	$(CC) $(CFLAGS) -o use_linked_list $(OBJ)

# remove files
clean : 
	rm -f *.o use_linked_list
